export const E = {
  AUTH_REQUIRED:'AUTH_REQUIRED', FORBIDDEN:'FORBIDDEN',
  INVALID_CREDENTIALS:'INVALID_CREDENTIALS', SESSION_EXPIRED:'SESSION_EXPIRED',
  PROJECT_NOT_FOUND:'PROJECT_NOT_FOUND', SHEET_NOT_FOUND:'SHEET_NOT_FOUND',
  TIME_SLOT_NOT_FOUND:'TIME_SLOT_NOT_FOUND', RESERVATION_NOT_FOUND:'RESERVATION_NOT_FOUND',
  QUEUE_NOT_FOUND:'QUEUE_NOT_FOUND', SCENE_NOT_FOUND:'SCENE_NOT_FOUND',
  DISPLAY_NOT_FOUND:'DISPLAY_NOT_FOUND', VALIDATION_ERROR:'VALIDATION_ERROR',
  CAPACITY_FULL:'CAPACITY_FULL', RESERVATION_NOT_ALLOWED:'RESERVATION_NOT_ALLOWED',
  TIME_SLOT_OVERLAP:'TIME_SLOT_OVERLAP', INVALID_TIME_RANGE:'INVALID_TIME_RANGE',
  SCENE_CONFIG_INVALID:'SCENE_CONFIG_INVALID', INVALID_STATE:'INVALID_STATE',
  ALREADY_ACCEPTED:'ALREADY_ACCEPTED', EXPIRED:'EXPIRED',
  QUEUE_CALL_CLOSED:'QUEUE_CALL_CLOSED', QUEUE_NORMAL_CALLING_CLOSED:'QUEUE_NORMAL_CALLING_CLOSED',
  CURRENT_CALLING_EXISTS:'CURRENT_CALLING_EXISTS', RECOVERY_NOT_ALLOWED:'RECOVERY_NOT_ALLOWED',
  EMERGENCY_CALL_NOT_ALLOWED:'EMERGENCY_CALL_NOT_ALLOWED',
  IDEMPOTENCY_CONFLICT:'IDEMPOTENCY_CONFLICT', VERSION_CONFLICT:'VERSION_CONFLICT',
  STATE_CONFLICT:'STATE_CONFLICT', INTERNAL_ERROR:'INTERNAL_ERROR',
} as const;
export type ErrorCode = typeof E[keyof typeof E];
const STATUS: Record<string,number> = {
  AUTH_REQUIRED:401, FORBIDDEN:403, INVALID_CREDENTIALS:401, SESSION_EXPIRED:401,
  PROJECT_NOT_FOUND:404, SHEET_NOT_FOUND:404, TIME_SLOT_NOT_FOUND:404,
  RESERVATION_NOT_FOUND:404, QUEUE_NOT_FOUND:404, SCENE_NOT_FOUND:404, DISPLAY_NOT_FOUND:404,
  VALIDATION_ERROR:400, CAPACITY_FULL:409, RESERVATION_NOT_ALLOWED:422,
  TIME_SLOT_OVERLAP:422, INVALID_TIME_RANGE:400, SCENE_CONFIG_INVALID:422,
  INVALID_STATE:422, ALREADY_ACCEPTED:409, EXPIRED:422,
  QUEUE_CALL_CLOSED:422, QUEUE_NORMAL_CALLING_CLOSED:422, CURRENT_CALLING_EXISTS:409,
  RECOVERY_NOT_ALLOWED:422, EMERGENCY_CALL_NOT_ALLOWED:422,
  IDEMPOTENCY_CONFLICT:409, VERSION_CONFLICT:409, STATE_CONFLICT:409, INTERNAL_ERROR:500,
};
export function errorResponse(code: ErrorCode, message: string, details?: unknown): Response {
  return Response.json({ ok:false, error:{ code, message, details } }, { status: STATUS[code]??500 });
}
export function successResponse<T>(data: T, status=200): Response {
  return Response.json({ ok:true, data }, { status });
}